[[redirects]]
  from = "/"
  to = "https://665.uncovernet.workers.dev/translate"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
